# Contributing

## Basics

You want to contribute? Awesome! Thanks for that!

Every contribution is required to be GPLv2 (or compatible) licensed (see COPYING). If you don't specify any license, GPLv2 will be assumed.

## How to suggest new features

Please create an issue first and wait for feedback before starting implementation. This avoids wasted effort on changes that won't be accepted.

## How to contribute code changes

Please fork the repository, implement your changes in a branch, and then submit a pull request.

### 🧪 Testing & Verification

- **Unit Tests:** We highly encourage including unit tests with your contributions. However, if your code was generated by an AI coding agent, unit tests are **mandatory**.
- **Integration Tests:** Wherever possible, functional/integration tests like those already in `tests/can-actually-be-used` **should** be created for new features.
- **Self-Verification:** Before committing, run local tests and linters to verify the code. Do not commit failing tests. Run `make test` to execute the full test suite (unit tests + Python tests). Integration tests in `tests/can-actually-be-used` use a virtual USB device via the `dummy-hcd` kernel module and **must** be run manually via `tests/can-actually-be-used/run-tests.sh`. Note that `dummy-hcd` is not included in every kernel build — if it is not available on your system, run `tests/can-actually-be-used/setup-dummyhcd.sh` first to build and install it as a DKMS module.
- **Platform Packaging:** Packaging on all platforms (Ubuntu, Fedora, Arch) **must** succeed. *(Note: contributors can verify this only locally with Docker, as CI does not cover this for forks.)*
  - How to verify: run `make build-{debian,fedora,arch}` (or `make build-all`)
- **Security & Linting:** DevSkim and other automated reviews **must** be either resolved or marked as false positive with reasoning.

### 🛡️ Code Quality & Scope

- **Strict Scoping:** Keep PRs strictly scoped to the requested feature or bug fix. Do not refactor unrelated code or change formatting outside the scope of the issue.
- **Dependencies:** Do not introduce new external dependencies unless strictly necessary and explicitly approved. Prefer standard library solutions.
- **Security Changes:** Any PR that touches security-relevant code **must** include a clear rationale for the change and describe the possible attack scenario it addresses or mitigates. Vague "security improvements" without a concrete threat model will not be accepted.

### 📝 Documentation

- **Keep it Updated:** Changes that introduce new config options or troubleshooting-relevant content **should** include updated documentation. Manpages **must** be updated manually; other docs are pulled from this repository's GitHub wiki via `make update-other-docs` (run only when your branch has no uncommitted changes).
- **General Rule:** If you think it could benefit from documentation → add it!

### 🔀 Git Workflow & PRs

- **Atomic Commits:** Keep commits atomic. Do not bundle massive changes into a single commit; break them down logically.
- **Issue Linking:** Every PR **must** reference the issue it addresses (e.g., `Closes #123` or `Refs #123` in the description). If there is no ticket for it please create one. If it's security related feel free to reference issue #55.
- **Assignee:** Assign the PR to yourself so it is clear who is responsible for it.
- **Reviewer:** Add @mcdope as a reviewer to signal the PR is ready for review. PRs without a reviewer assigned are treated as draft/WIP and will not be reviewed.
- **Labels:** Add labels matching the type of change (e.g., `bug`, `enhancement`, `documentation`). If no suitable label exists, use the closest match.
- **PR Descriptions (Reasoning):** PR descriptions **should** include a brief summary of *why* a specific technical approach was chosen, especially if it alters core logic.
- **PR Descriptions (Security):** If your PR addresses a security concern, the description **must** explicitly state the attack scenario (who can exploit it, how, and what the impact is). "This improves security" is not sufficient.

### 🤖 AI-Assisted Contributions

*If you are using AI tools (e.g., Claude, Cursor, Aider) to write code for your PR, you **must** adhere to the following additional rules:*

- **Commit Attribution:** AI-assisted commits **must** be marked with `Co-authored-by`. Use `NameOfTheAI <NameOfTheAI@example.com>` for the value (or the proper email address if there is one).
- **PR Descriptions (Tagging):** Add a note in the PR description indicating that an AI coding agent assisted with the PR (e.g., `🤖 This PR was generated with the assistance of [AI Name]`).
- See also "Testing & Verification" — AI contributions **must** include unit tests at minimum.
- As soon as **ANY** of these guidelines isn't fulfilled, I will just close your PR.

### 🍏 I use a Mac so I / my AI can't handle PAM stuff locally

I don't care. Set up a VM. If you want to work on code for Linux, you need Linux, at least for testing — it's as simple as that. There are even Docker definitions you could simply use.

## How to contribute documentation

The Wiki should be editable by anyone — feel free to just work on it. In case you want to work on the manpages: these are managed in code. See "How to contribute code changes" above.