FROM fedora:30

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/entrypoint.sh"]

ENV TERM=xterm
WORKDIR /usr/local/src/pam_usb

RUN dnf upgrade --refresh -y
RUN dnf install -y gcc make rsync libxml2-devel pam-devel libudisks2-devel glib2-devel python3-gobject rpmdevtools rpmlint