FROM fedora:40
ENV TERM=xterm
WORKDIR /usr/local/src/pam_usb

RUN --mount=type=cache,id=dnf-fedora-ppc64el,target=/var/cache/dnf,sharing=locked \
    dnf install -y gcc make libxml2-devel pam-devel libudisks2-devel glib2-devel libevdev-devel python3-gobject rpmdevtools rpmlint
RUN printf '%%_lto_cflags %%{nil}\n%%_smp_mflags -j1\n%%optflags -O2 -g -pipe -Wall -Wformat -Werror=format-security -fstack-protector-strong\n' > /etc/rpm/macros.no-lto
