FROM fedora:40
ENV TERM=xterm
WORKDIR /usr/local/src/pam_usb

RUN dnf install -y gcc make libxml2-devel pam-devel libudisks2-devel glib2-devel libevdev-devel python3-gobject rpmdevtools rpmlint && \
    dnf clean all
