FROM menci/archlinuxarm:base-devel
ENV TERM=xterm
WORKDIR /usr/local/src/pam_usb

RUN useradd -m builduser && \
    pacman-key --init && \
    pacman --noconfirm -Sy archlinux-keyring && \
    pacman --noconfirm -S --needed --overwrite '/usr/lib/libgcc_s.so*,/usr/lib/libstdc++.so*' sudo git pkgconf gcc make patch pam dbus python python-dbus python-lxml python-gobject udisks2 libevdev base-devel pacman-contrib
