FROM fedora:30
ENV TERM=xterm
WORKDIR /usr/local/src/pam_usb

RUN --mount=type=cache,id=dnf-fedora,target=/var/cache/dnf,sharing=locked \
    dnf install -y gcc make libxml2-devel pam-devel libudisks2-devel glib2-devel libevdev-devel python3-gobject rpmdevtools rpmlint
