.TH pamusb-pinentry 1 "November 03, 2024" "" "PAM_USB"

.SH NAME
\fBpamusb-pinentry \fP- pam_usb tool to be used as pinentry application
.SH SYNOPSIS
\fBpamusb-pinentry\fP [\fB--install\fP | \fB--uninstall\fP]
.SH DESCRIPTION
\fBpamusb-pinentry\fP is a tool to unlock your GPG keyring when used with pam_usb autologin.
When invoked without options it operates as a pinentry program (communicating via the Assuan protocol on stdin/stdout).
.SH OPTIONS
.TP
\fB--install\fP
Create the envfile (\fI~/.pamusb/.pinentry.env\fP) with a template configuration (permissions 0600) and, if \fBupdate-alternatives\fP(1) is available, register and activate \fBpamusb-pinentry\fP as the system pinentry alternative.
The envfile is always created in the invoking user's home directory (using \fBSUDO_USER\fP when run via sudo).
The \fBupdate-alternatives\fP step requires root privileges.
.TP
\fB--uninstall\fP
Remove the envfile (\fI~/.pamusb/.pinentry.env\fP) and, if \fBupdate-alternatives\fP(1) is available, deregister the \fBpamusb-pinentry\fP pinentry alternative.
The envfile path is resolved via \fBSUDO_USER\fP when run via sudo.
The \fBupdate-alternatives\fP step requires root privileges.
.SH CONFIGURATION
See the pam_usb Wiki <https://github.com/mcdope/pam_usb/wiki/Getting-Started#auto-unlock-your-gpg-keys> for details about how to configure this feature.
.SH BUGS
Please post bug reports on the Github issue tracker.
.SH AUTHOR
Tobias Bäumer <tobiasbaeumer@gmail.com>
