#!/usr/bin/env python3
import os
import subprocess
import getpass
from dotenv import load_dotenv
load_dotenv("~/.pamusb-pinentry.env")

pinentryPassword = os.getenv('PINENTRY_PASSWORD')
fallbackPinentryApp = os.getenv('PINENTRY_FALLBACK_APP')

isAuthenticated = subprocess.run(["pamusb-check", getpass.getuser()], capture_output=True)
if (isAuthenticated.returncode == 0):
    print("OK Pleased to meet you")
    while True:
        line = input().split()
        if line[0] == "GETPIN":
            print("D %s" % pinentryPassword)
        elif line[0] == "BYE":
            exit()
        print("OK")
else:
    subprocess.run(fallbackPinentryApp)