#!/bin/sh

# Check if password file exists and has correct permissions
if [ ! -f ~/.keyring_unlock_password ]; then
    logger -p local0.notice -t ${0##*/}[$$] No password file found, exiting.
    exit 0
fi

PERMISSIONS=`stat -c "%a %n" ~/.keyring_unlock_password | awk '{print $1}'`
if [ ! "$PERMISSIONS" = "600" ]; then
    logger -p local0.error -t ${0##*/}[$$] Bad permissions on ~/.keyring_unlock_password. Please change them to 0600.
    exit 1
fi

# Kill existing keyring instance
killall -q gnome-keyring-daemon

# Read UNLOCK_PASSWORD from ~/.keyring_unlock_password
. ~/.keyring_unlock_password

# Perform unlock
echo -n $UNLOCK_PASSWORD | gnome-keyring-daemon --daemonize --login \
    && gnome-keyring-daemon --start; UNLOCKED=$? \
    && logger -p local0.notice -t ${0##*/}[$$] Keyring unlocked. \
    || logger -p local0.error -t ${0##*/}[$$] Keyring unlock failed.

exit $UNLOCKED
