name: Can be packaged successfully

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install libudisks2-dev libxml2-dev python libpam0g-dev devscripts debhelper dh-systemd
    - name: make deb
      run: make deb
    - name: check that deb can be installed
      run: sudo apt install ../*.deb
    . name: check that installed package can be used
      run: cd tests/can-actually-be-used && ./run-tests.sh

