name: Can be packaged successfully

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jammy:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install libudisks2-dev libxml2-dev python libpam0g-dev devscripts debhelper dh-systemd pkg-config gir1.2-glib-2.0 libglib2.0-dev
    - name: make deb
      run: make deb
    - name: check that deb can be installed
      run: sudo apt install ../*.deb
