name: Can be built successfully

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jammy:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      uses: ./.github/actions/install-build-deps
    - name: make
      run: make
