name: Can be packaged successfully

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install libudisks2-dev libxml2-dev python libpam0g-dev devscripts debhelper dh-systemd dkms pkg-config gir1.2-glib-2.0 libglib2.0-dev
    - name: make deb
      run: make deb
    - name: check that deb can be installed
      run: sudo apt install ../*.deb
    # - name: setup g_mass_storage module for fake usb stick
    #   run: cd tests/can-actually-be-used && ./setup-dummyhcd.sh
    # - name: load dummy-hcd module
    #   run: cd tests/can-actually-be-used && ./prepare-mounting.sh
    # - name: create fake usb stick image
    #   run: cd tests/can-actually-be-used && ./create-image.sh
    # - name: insert and mount fake usb stick
    #   run: cd tests/can-actually-be-used && ./mount-image.sh
    # - name: check that installed package can be used
    #   run: cd tests/can-actually-be-used && ./run-tests.sh

