name: Python tools linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install libudisks2-dev libxml2-dev python libpam0g-dev
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run pylint
      run: |
        cd tools
        pylint `ls -R|xargs`
